### PR TITLE
Redirect expiring users to login

### PR DESCRIPTION
**Pull request by adamcunnington**

### CODE REVIEW

**Comment by adamcunnington** [comment]
@mbarton as discussed, I've made a small change to backend so we require users to login if the expiry time provided by google auth is <= now.

Can you handle the potential redirect that you may receive in an ajax request? I guess you can just redirect user to login but not sure if it's worth notifying them somehow. Most of the time, their re-login will be seamless because Google will probably just respond with an updated expiry time but in this case, they may be confused why their page has been seemingly refreshed etc. But if this is non-trivial, can be considered a later improvement for sure.

**Comment by adamcunnington** [comment]
@mbarton is this an easy one to accommodate?

**Comment by mbarton** [comment]
Shouldn’t be complicated yeah, I can write a fetch wrapper that traps redirect to login and updates window.location accordingly. I’ll give it a go this weekend

**Comment by mbarton** [comment]
@adamcunnington in the end I think we needed to also add the check to the `login_required` decorator wrapping the `bff` and `api`. As that already returned `403` that's what I trap on the client side and move the user to the `/login` page

**Comment by adamcunnington** [comment]
@mbarton good catch! Merging

**Pull request merged**
